"""Add column_mapping to trace_jobs

Revision ID: fdeb741cb3d6
Revises: 80cb76703cce
Create Date: 2026-05-12 16:28:18.625348+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fdeb741cb3d6'
down_revision = '80cb76703cce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace_jobs', sa.Column('column_mapping', sa.Text(), nullable=True))
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'reset_token_expires')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token_expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('trace_jobs', 'column_mapping')
    # ### end Alembic commands ###
